apiVersion: v1
kind: ConfigMap
metadata:
  name: node-tasker
data:
  task: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-tasker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-tasker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-tasker
    spec:
      serviceAccount: node-tasker
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      containers:
      - name: tasker
        image: dockerhub.azk8s.cn/alexzhc/node-tasker
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: THIS_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: THIS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: THIS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: run
          mountPath: /var/local/run
        lifecycle:
          preStop:
            exec:
              command:
              - entry.sh
              - --cleanup-only
      volumes:
      - name: run
        configMap:
          name: node-tasker
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node/task
      #           operator: Exists