apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-tasker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-tasker
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-tasker
subjects:
  - kind: ServiceAccount
    name: node-tasker
roleRef:
  kind: Role
  name: node-tasker
  apiGroup: rbac.authorization.k8s.io